### ISSUE TITLE
In IOS the uri of photos selected from gallery is showing null

### ISSUE THREAD

**Issue by vijay2330** [prancky/expo-multiple-imagepicker#1]
I tries to select multiple photos from gallery.... In Android it works fine but in IOS after the image selected the uri of each image is showing null.........

Code:

      
      imageBrowserCallback = (callback) => {
       callback.then(async (photoRoll) => {
        console.warn(photoRoll)    // here the uri is shown as null

      let selected = photoRoll.map(async ({uri})=>{
        let resize = await this.resizeImage(uri)
        return {
          photo: resize.uri,
          state: true
        }
     })

     Promise.all(selected).then((result)=>{      
      let photos = [...this.state.photos,...result];
      this.setState({
        imageBrowserOpen: false,
        photos
      });
      this.props.addPhotos(photos);
     })      
    }).catch((e) => console.log(e))
  }

 Is there any solution???

**Comment by pmalliak** [comment]
@vijay2330 Hello there, did you find any solution to this?
